# @package _global_

# Nsynth large-capacity model for GPUs with more available VRAM.

module: main.diffusion_module
batch_size: 1
accumulate_grad_batches: 32
num_workers: 0

sampling_rate: 16000
length: 16384
channels: 2
val_log_every_n_steps: 1000

model:
  _target_: ${module}.Model
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  ema_beta: 0.995
  ema_power: 0.7

  model:
    _target_: audio_diffusion_pytorch.DiffusionModel
    net_t:
      _target_: ${module}.UNetT
    in_channels: 2
    channels: [64, 64, 128, 128, 256, 256, 384, 384]
    factors: [1, 2, 2, 2, 2, 2, 2, 2]
    items: [2, 2, 2, 2, 2, 2, 4, 4]
    attentions: [0, 0, 0, 0, 1, 1, 1, 1]
    attention_heads: 8
    attention_features: 128

datamodule:
  _target_: main.diffusion_module.Datamodule
  dataset:
    _target_: main.diffusion_module.NsynthWavDataset
    path: ${data_dir}/nsynth_guitar/wav_dataset
    recursive: True
    sample_rate: ${sampling_rate}
    crop_size: ${length}
    stereo: True
  val_split: 0.1
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  pin_memory: True

callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.TQDMProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid_loss"
    save_top_k: 1
    save_last: True
    mode: "min"
    verbose: False
    dirpath: ${logs_dir}/ckpts/${now:%Y-%m-%d-%H-%M-%S}
    filename: '{epoch:02d}-{valid_loss:.3f}'

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2

  audio_samples_logger:
    _target_: main.diffusion_module.SampleLogger
    num_items: 4
    channels: ${channels}
    sampling_rate: ${sampling_rate}
    length: ${length}
    sampling_steps: [50]
    use_ema_model: True

loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: ${oc.env:WANDB_PROJECT,nsynth_baseline}
    entity: ${oc.env:WANDB_ENTITY,}
    name: nsynth_guitar_large_diffusion
    job_type: "train"
    group: ""
    save_dir: ${logs_dir}

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 0
  precision: 16
  num_sanity_val_steps: 0
  min_epochs: 0
  max_epochs: -1
  enable_model_summary: False
  log_every_n_steps: 1
  check_val_every_n_epoch: null
  val_check_interval: ${val_log_every_n_steps}
  accumulate_grad_batches: ${accumulate_grad_batches}